
version: '2'

services:
  django-uwsgi-nginx:
    # image: django-uwsgi-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/home/docker/code
    ports:
      - 8080:80
    # command: bash